{% set name = "ipyaladin" %}
{% set version = "0.1.4" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "64f684a8c24f574e35f1285c0ca40e45fc28c4e9dca7a304b7b46f1e25607492" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - ipywidgets >=6.0.0
  run:
    - python
    - ipywidgets >=6.0.0
    - astropy

test:
  imports:
    - ipyaladin

about:
  home: https://github.com/cds-astro/ipyaladin
  license: BSD-3-Clause
  license_family: BSD
  license_file: ''
  summary: ipyaladin
  description: ipyaladin, a Jupyter widget for Aladin Lite
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers:
    - tboch

